language: php

dist: focal
sudo: required

cache:
    directories:
        - vendor
        - bin

php:
    - 8.0

install:
    - sudo apt-get update
    - cd $TRAVIS_BUILD_DIR
    - composer self-update
    - composer install --optimize-autoloader --prefer-dist --no-scripts

before_script:
    - echo "xdebug.mode = coverage" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
    - bin/atoum -ulr

