on: push
name: Static Analysis

jobs:
  phpcsfixer:
    name: PHP Coding Standards Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH }}' > $GITHUB_WORKSPACE/auth.json
      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer
      - name: Install dependencies
        run: composer install --no-interaction --no-progress
      - name: PHP Coding Standards Fixer
        run: bin/php-cs-fixer fix --dry-run --diff

  phpstan:
    name: PHPStan Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH }}' > $GITHUB_WORKSPACE/auth.json
      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer
      - name: Install dependencies
        run: composer install --no-interaction --no-progress
      - name: PHPStan Static Analysis
        run: bin/phpstan --memory-limit=1G --error-format=github
